"""initial

Revision ID: dcc8660907f6
Revises: 
Create Date: 2024-12-08 19:34:38.463286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dcc8660907f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'accountType',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'chineseName',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'englishName',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('users', 'birthday',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'studentId',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_column('users', 'username')
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=50), nullable=True))
    op.alter_column('users', 'studentId',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'birthday',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('users', 'gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('users', 'englishName',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'chineseName',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'accountType',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
